### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by martinmodrak** [matthew798/formr#1]
Hi,
I just stumbled upon your repository while searching for some advanced uses of [FormR - form library closely tied to the R language](https://github.com/rubenarslan/formr.org) - while not exactly a famous framework, it is reasonably established in the psychology/open science community. Would you consider renaming your early project? Obviously there is no obligation on your side and you can keep the name if you wish, I just think both your project and the R FormR community would benefit from avoiding this competition.

Best of luck with your coding!

P.S.: I am not affiliated with FromR, just using it for a project.

**Comment by matthew798** [comment]
Hi!

Thanks for pointing that out. At this point, the name is much too integrated with the codebase to be changed. I will, however, add a disclaimer to the top of the readme. Thanks!
